
export const GIF_URLS = [
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_2.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_3.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_4.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_5.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_6.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_7.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_8.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_9.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_10.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_11.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_12.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_13.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/hq_14.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/sq_5.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/sq_6.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/sq_8.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/sq_11.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/sq_13.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/sq_14.gif?raw=true",
 "https://github.com/CodaBool/cloudflare/blob/main/cron/img/sq_15.gif?raw=true",
]
