name = "discord"
main = "main.js"
compatibility_date = "2023-12-01"
node_compat = true
# compatibility_flags = [ "nodejs_compat" ]

[vars]
DOMAIN = "discord.codabool.workers.dev"
PUBLIC_KEY = "c2485dc3e3adccd7d92aa4836260aa5c2338f37a05c1690bbae7b2799da19333"
