name: analytics
on:
  push:
    branches:
      - main
    paths:
      - "analytics/**"
jobs:
  release:
    if: "! contains(github.event.commits[0].message, '[no ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          workingDirectory: analytics
          command: deploy