name: d3erver
on:
  push:
    branches:
      - main
    paths:
      - "d3erver/**"
jobs:
  release:
    if: "! contains(github.event.commits[0].message, '[no ci]')"
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/setup-node-js-environment
      - uses: actions/setup-node@v4
      - run: npm ci
        working-directory: d3erver
      - name: test
        run: |
          npx wrangler dev \
            --var FOUNDRY_SECRET:$FOUNDRY_SECRET \
            --var FORGE_SECRET:$FORGE_SECRET \
            --var TEST:$TEST &
          sleep 5
          npx mocha
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          TEST: ${{ secrets.TEST }}
          FOUNDRY_SECRET: ${{ secrets.FOUNDRY_SECRET }}
          FORGE_SECRET: ${{ secrets.FORGE_SECRET }}
        working-directory: d3erver
      # https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          workingDirectory: d3erver
          command: deploy