on:
  push:
    paths:
      - d3server/**
jobs:
  release:
    if: "! contains(github.event.commits[0].message, '[no ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: npm ci
        working-directory: d3erver
      - run: npm test
        env:
          DB_USER: ${{ secrets.POSTGRES_USER }}
          DB_HOST: ${{ secrets.POSTGRES_HOST }}
          DATABASE: ${{ secrets.POSTGRES_DB }}
          DB_HMAC: ${{ secrets.POSTGRES_PASSWORD }}
          DB_PORT: ${{ secrets.POSTGRES_DB_PORT }}
          DB_DIALECT: ${{ secrets.POSTGRES_DB_DIALECT }}
          DB_POOL_CONNECTION_LIMIT: ${{ secrets.POSTGRES_DB_POOL_CONNECTION_LIMIT }}
          DB_POOL_IDLE_TIMEOUT: ${{ secrets.POSTGRES_DB_POOL_IDLE_TIMEOUT }}
          APP_PORT: ${{ secrets.NODE_APP_PORT }}
        working-directory: d3erver
      - run: "ran"
      # - uses: cloudflare/wrangler-action@v3
      #   working-directory: d3erver
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
      #     command: deploy