name: d3erver
on:
  push:
    branches:
      - main
    paths:
      - "d3erver/**"
jobs:
  release:
    if: "! contains(github.event.commits[0].message, '[no ci]')"
    runs-on: ubuntu-latest
    # pipeline:
    #   name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    #   runs-on: ${{ matrix.os }}

    #   strategy:
    #     fail-fast: false
    #     matrix:
    #       node-version: ['20.x']
    #       os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: npm i
        working-directory: d3erver
      - run: |
          npx wrangler dev &
          sleep 4s
          npx mocha
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          TEST: ${{ secrets.TEST }}
          FOUNDRY_SECRET: ${{ secrets.FOUNDRY_SECRET }}
          FORGE_SECRET: ${{ secrets.FORGE_SECRET }}
        working-directory: d3erver

      # - uses: sambacha/parallelish@v1.0.0
      #   with:
      #     cmd1: cd d3erver && npm run wait-test;
      #     cmd2: cd d3erver && npm run dev;
      #   env:
      #     DOMAIN: ${{ secrets.DOMAIN }}
      #     TEST: ${{ secrets.TEST }}
      #     FOUNDRY_SECRET: ${{ secrets.FOUNDRY_SECRET }}
      #     FORGE_SECRET: ${{ secrets.FORGE_SECRET }}
      - run: "echo 'ran'"
      # - uses: cloudflare/wrangler-action@v3
      #   working-directory: d3erver
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
      #     command: deploy