on:
  push:
    paths:
      - d3erver
jobs:
  release:
    if: "! contains(github.event.commits[0].message, '[no ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: npm ci
        working-directory: d3erver
      - run: npm test
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          TEST: ${{ secrets.TEST }}
          FOUNDRY_SECRET: ${{ secrets.FOUNDRY_SECRET }}
          FORGE_SECRET: ${{ secrets.FORGE_SECRET }}
        working-directory: d3erver
      - run: "echo 'ran'"
      # - uses: cloudflare/wrangler-action@v3
      #   working-directory: d3erver
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
      #     command: deploy